CREATE TABLE USER_RELATION(
USER_ID NUMBER NOT NULL,
CONSTRAINT USER_FM_FK FOREIGN KEY(USER_ID)REFERENCES USER_FM(USER_ID),
RELATION_ID NUMBER NOT NULL,
CONSTRAINT RELATIONSHIP_FK FOREIGN KEY(RELATION_ID)REFERENCES RELATIONSHIP(RELATIONSHIP_ID)
);