CREATE TABLE USER_FM(
 USER_ID NUMBER NOT NULL PRIMARY KEY,
 USER_FIRST_NAME NVARCHAR2(20) NOT NULL,
 USER_LAST_NAME NVARCHAR2(50) NOT NULL,
 PHONE NVARCHAR2(15) NOT NULL,
 COUNTRY NVARCHAR2(30) NOT NULL,
 CITY NVARCHAR2(30) NOT NULL,
 AGE NUMBER NOT NULL,
 DATE_REGISTERED TIMESTAMP NOT NULL,
 DATE_LAST_ACTIVE TIMESTAMP NOT NULL,
 RELATIONSHIP_TYPE NVARCHAR2(10) NOT NULL CHECK(RELATIONSHIP_TYPE = 'single' OR RELATIONSHIP_TYPE = 'married'),
 RELIGION_TYPE NVARCHAR2(20) NOT NULL,
 SCHOOL NVARCHAR2(30) NOT NULL,
 UNIVERSITY NVARCHAR2(30) NOT NULL
);

CREATE SEQUENCE USER_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;