/*CREATE TABLE RELATIONSHIP(
RELATIONSHIP_ID NUMBER NOT NULL PRIMARY KEY,
ID_USER_FROM NUMBER,
CONSTRAINT RELATIONSHIP_USER_FROM_FK FOREIGN KEY (ID_USER_FROM)REFERENCES USER_FM(USER_ID),
ID_USER_TO NUMBER,
CONSTRAINT RELATIONSHIP_USER_TO_FK FOREIGN KEY (ID_USER_TO)REFERENCES USER_FM(USER_ID),
STATUS_TYPE NVARCHAR2(30) NOT NULL CHECK (STATUS_TYPE = 'never_been_friends' OR
STATUS_TYPE = 'were_once_friends' OR STATUS_TYPE = 'request_has_been_sent' OR
STATUS_TYPE = 'request_rejected' OR STATUS_TYPE = 'friends')
);*/

/*While replaced by this*/
CREATE TABLE RELATIONSHIP(
  RELATIONSHIP_ID NUMBER NOT NULL PRIMARY KEY,
  USER_FROM_RELATIONSHIP NUMBER,
  --CONSTRAINT RELATIONSHIP_USER_FROM_FK FOREIGN KEY (ID_USER_FROM)REFERENCES USER_FM(USER_ID),
  USER_TO_RELATIONSHIP NUMBER,
  --CONSTRAINT RELATIONSHIP_USER_TO_FK FOREIGN KEY (ID_USER_TO)REFERENCES USER_FM(USER_ID),
  STATUS_TYPE NVARCHAR2(30) NOT NULL CHECK (STATUS_TYPE = 'never_been_friends' OR
  STATUS_TYPE = 'were_once_friends' OR STATUS_TYPE = 'request_has_been_sent' OR
  STATUS_TYPE = 'request_rejected' OR STATUS_TYPE = 'friends')
);

CREATE SEQUENCE RELATIONSHIP_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;
DROP SEQUENCE RELATIONSHIP_SEQ;