CREATE TABLE POST(
 POST_ID NUMBER NOT NULL PRIMARY KEY,
 ID_USER_POSTED NUMBER NOT NULL,
 CONSTRAINT USER_POSTED_FK FOREIGN KEY(ID_USER_POSTED)REFERENCES USERS1(USER_ID),
 ID_USER_PAGE_POSTED NUMBER NOT NULL,
 CONSTRAINT USER_PAGE_POSTED_FK FOREIGN KEY(ID_USER_PAGE_POSTED)REFERENCES USERS1(USER_ID),
 MESSAGE NVARCHAR2(200) NOT NULL,
 LOCATIONS NVARCHAR2(300) NOT NULL,
 DATE_POSTED TIMESTAMP NOT NULL
);

CREATE SEQUENCE POST_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;