CREATE TABLE POST(
 POST_ID NUMBER NOT NULL PRIMARY KEY,
 ID_USER_POSTED NUMBER,
 CONSTRAINT USER_POSTED_FK FOREIGN KEY(ID_USER_POSTED)REFERENCES USER_FM(USER_ID),
 MESSAGE NVARCHAR2(800) NOT NULL,
 DATE_POSTED TIMESTAMP NOT NULL
);

CREATE SEQUENCE POS_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;